[project]
name = "example-mongoengine"
version = "0.1.0"
description = "MongoEngine Example."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask-admin[mongoengine]",
    "testcontainers[mongodb]"
]

[tool.uv.sources]
flask-admin = { path = "../../", editable = true }
