[project]
name = "example-geo-alchemy"
version = "0.1.0"
description = "GeoAlchemy Example."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flask-admin[sqlalchemy-with-utils,geoalchemy]",
    "psycopg2",
]

[tool.uv.sources]
flask-admin = { path = "../../", editable = true }
