[project]
name = "example-methodview"
version = "0.1.0"
description = "MethodView Example."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flask-admin",
]

[tool.uv.sources]
flask-admin = { path = "../../", editable = true }
