[project]
name = "example-datetime-timezone"
version = "0.1.0"
description = "Datetime Timezone Example."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flask-admin[sqlalchemy]",
]

[tool.uv.sources]
flask-admin = { path = "../../", editable = true }
