[project]
name = "example-babel"
version = "0.1.0"
description = "Flask-Babel Integration Example."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask-admin[sqlalchemy-with-utils,translation]",
]

[tool.uv.sources]
flask-admin = { path = "../../", editable = true }
