[project]
name = "example-csp-nonce"
version = "0.1.0"
description = "CSP Nonce Example."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask-admin",
    "flask-talisman",
]

[tool.uv.sources]
flask-admin = { path = "../../", editable = true }
